### ISSUE TITLE
Have LSL have a regular release cadence (weekly, biweekly) and print a warning when running "out of date" version

### ISSUE THREAD

**Issue by dbp** [logiccomp/lsl#14]
If we hardcoded, in the code, a date after which the code should be updated, we should be able to have it print out a warning in the interactions window that the students should update. As long as we fix a release cadence, this seems like it might be easier to ensure students are regularly updating if they get actual feedback every time they run a program using an out of date version. 

(This depends on their computer date being accurate within a day or two, but that seems like a fine assumption).

**Comment by camoy** [comment]
Another possibility might be to check with the Github for the latest tagged release. It's probably a bad idea to do this every time you run a program. However, we could use the language info mechanism to only send a request when DrRacket loads the `#lang`, which should happen just once per opened file.

**Comment by dbp** [comment]
Hmm. I had thought about doing a network request, but probably it’s reliable enough, and would allow us to not force unnecessary updates.

**Comment by camoy** [comment]
I've implemented this by pinging Github for a [JSON file](https://github.com/logiccomp/lsl/blob/main/lsl-lib/version.json) containing the version and comparing against the local copy of the same JSON. Version checks are inserted into modules via `#%module-begin` (trying to do this with language info turned out not to be possible, or at least I couldn't figure it out). To prevent flooding with HTTP requests, versions are cached for one hour.

**Comment by dbp** [comment]
Great!
